# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cl_Item_ID', models.CharField(max_length=1000)),
                ('KeyParam', models.CharField(max_length=45)),
                ('ValueParam', models.CharField(max_length=10000)),
                ('ScrapedDateTime', models.CharField(max_length=45)),
                ('RSS_Feed_String', models.CharField(max_length=1000)),
            ],
        ),
    ]
